version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init_scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=recordings
      - TZ=Asia/Tokyo