version: '3.8'

services:

  mysql_server:
    user: mysql
    build: ./mysql_server
    container_name: mysql_server
    volumes:
      - ./mysql_server/log:/var/log/mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    networks:
      - net

  adminer:
    build: ./adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - net

networks:
  net:
