version: '3.8'

services:

  redis:
    build: ./redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - net

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    platform: linux/amd64
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - net

networks:
  net:
